[package]
name = "amaru-yara-engine"
version = "0.1.0"
edition = "2021"
authors = ["Amaru Contributors"]
description = "YARA integration for Amaru Antivirus"
license = "GPL-2.0"
build = "build.rs"

[dependencies]
# YARA bindings
yara = "0.22"
# Error handling
anyhow = "1.0"
thiserror = "1.0"
# Logging
log = "0.4"
# Serialization
serde = { version = "1.0", features = ["derive"] }
# Parent crate
amaru = { path = ".." }

[build-dependencies]
cc = "1.0"

[lib]
name = "amaru_yara_engine"
path = "src/lib.rs" 